name: Robert Poole
markdown: kramdown
theme: jekyll-theme-architect
title: Rob's Blog
description: programming (mostly web development)
permalink: /:title/

defaults:
  -
    values:
      layout: "default"
