name: Robert Poole
markdown: kramdown
theme: jekyll-theme-slate
title: Rob's Blog
description: programming (mostly web development)
permalink: /:title/

defaults:
  -
    values:
      layout: "default"

plugins:
  - jekyll-target-blank
